#!/bin/bash
export TEST_IMAGE_ID=034f7d4d-4ec2-424d-bbff-a4b8809dc01d
export TEST_FLAVOR=m1.small
export TEST_SEC_GROUP=sa-test
export TEST_KEY_NAME=ray_nectar
export TEST_KEY_FILE=ray_nectar.pem
export TEST_AVA_ZONE=sa
export TEST_INSTANCE_NAME_BASE=lei-test-BBB
export TEST_INSTANCE_USER=ubuntu
export retry_max=10
export retry_interval=3
